Homework 3
AGENTxXx/CourseProject pull request #2
Opened 2020-11-30 18:40 UTC by AGENTxXx

Fragments, movies list, load some resources

2020-12-02 00:38 UTC, Vladuken requested changes
Просмотрел

Постарался максимально подробно описать. 

Из оставшегося - png заменить на webp + изначальные png у тебя низкого качества, скачай с фигмы png высокого качества (поставь x4 как на скрине, либо еще больше)
<img width="209" alt="image" src="https://user-images.githubusercontent.com/23121846/100813184-cc533d00-344f-11eb-9012-384b55ad29af.png">

2020-12-02 00:38 UTC, Vladuken commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
ненужная зависимость, можно удалить

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/res/drawable/card_grad.xml
> +    <stroke android:width="1dp" android:color="#363646"/>
Этот цвет уже есть в colors.xml можно сослаться

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/res/drawable/ic_aim.xml
> +        <item android:offset="0" android:color="#FF3466"/>
Здесь тоже можно вынести из colors.xml

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/res/drawable/ic_liked.xml
> +      android:fillColor="@color/red_radical"
Кстати, есть еще один вариант как можно делать:

Оставить один ресурс для сердечка, но уже у него менять параметр tint (как видишь, этому shape-у можно любой цвет сделать, а сам второй ресурс ic_liked удалить, чтобы поменьше дублирования было)- 
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/23121846/100809484-492de900-3447-11eb-97c4-f6d5b3906407.png">

То что красным выделилось - это у меня андроид студия залагала, так то все ок должно быть

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="match_parent"
У тебя все еще это лежит в constraint-layout-е, так что можешь указать 0dp

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/res/layout/activity_main.xml
> +    </FrameLayout>
Так как тег фрейм лейаут пустой, ты можешь его сразу же закрыть, а не на отдельной строке
<img width="397" alt="image" src="https://user-images.githubusercontent.com/23121846/100809878-3e278880-3448-11eb-80f6-136dccfd5cbb.png">

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/res/values/strings.xml
> +    <string name="movie_list_movies_list">Movies list</string>
вообще у тебя все эти строки вроде уже выше были, ты можешь просто их переиспользовать, а не дублировать.

Отвечают то они за одно и то же

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/MainActivity.kt
> +    private lateinit var fragmentMoviesDetails:FragmentMoviesDetails
1. У тебя нет смысла хранить ссылку на фрагмент внутри акстивити и присваивать ее, ты можешь сразу сетить фрагмент в менеджере.

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/MainActivity.kt
> +            fragmentMoviesList = FragmentMoviesList().apply { setClickListener(this@MainActivity) }
2. здесь добавь чтобы FragmentMoviesList не через конструктор вызывался, а через  метод companion object-а
`FragmentMoviesList.newInstance()`

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/MainActivity.kt
> +            fragmentMoviesList = FragmentMoviesList().apply { setClickListener(this@MainActivity) }
3. Вместо того чтобы сетить clickListener из Активити в фрагмент, ты можешь внутри фрагмента получить ссылку на activity, проверить что она реализует ClickListener, и тогда уже засетить листенер внутри фрагмента. 

Вот примерно как это выглядит(и происходит все это внутри фрагмента, а не activity):
<img width="390" alt="image" src="https://user-images.githubusercontent.com/23121846/100810551-c9554e00-3449-11eb-9c3d-898d6317a823.png">

<img width="275" alt="image" src="https://user-images.githubusercontent.com/23121846/100810573-d40fe300-3449-11eb-931a-6a4ba60268a6.png">

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/MainActivity.kt
> +    }
4. Вот этот весь код с тегами, и восстановлениями можно удалить будет, потому что при перевороте фрагмент менеджер сам пересоздаст фрагмент который в стеке+ так как фрагмент сам сетит clickListener, то оно при перевороте будет продолжать работать с кликами.

В итоге onCreate будет выглядеть как-то так и без лишнего кода:
<img width="675" alt="image" src="https://user-images.githubusercontent.com/23121846/100810742-294bf480-344a-11eb-9fb0-41835c645d53.png">

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/MainActivity.kt
> +        fragmentMoviesDetails = FragmentMoviesDetails().apply { setClickListener(this@MainActivity) }
5. Здесь тоже сделай FragmentMoviesDetails.newInstance() 
И кликлистенер вообще можно убрать (дальше опишу почему)

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/MainActivity.kt
> +    }
6. вот это тоже можно убрать ,потому что внутри фрагмента ты можешь получить ссылку на activity в которой лежит фрагмент и сразу там вызвать onBackPressed()

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesList.kt
> +    }
можешь onCreate удалить, потому что ты его переопределяешь, но ничего в нем не меняешь, так что ничего не изменится.

Вместо onCreate лучше сделай onAttach() в котором будешь сетить кликлистенер (учти что Активити в таком случае должна реализовывать CardFragmentClickListener)

Выглядеть будет примерно вот так:
<img width="346" alt="image" src="https://user-images.githubusercontent.com/23121846/100811111-ed655f00-344a-11eb-8c2e-2dd989df91a2.png">

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesList.kt
> +                              savedInstanceState: Bundle?): View? {
можешь нажать CTRL+ALT+L для автореформатинга кода + выработать у себя привычку время от времени нажимать это сочетания, чтобы отреформатировать код красиво

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesList.kt
> +    }
этот метод можно будет удалить вообще , он нам больше не нужен

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesList.kt
> +
не забудь onDetach() и в нем присвоить null переменной с clickListener-ом
на всякий случай

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +
Здесь если что работают все те же комментарии что и в FragmentMovieList

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +    private var listener: OnBackPressedListener? = null
Это можно убрать вообще

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +    }
этот код тоже можно убрать

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +                listener?.doBack()
можно убрать apply {} а сразу setOnClickListener поставить 

+ вместо listener?.doBack() можно requireActivity().onBackPressed()

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +    }
Вот этот код тоже не нужен вообще

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/res/drawable/ic_star_off_small.xml
> +</vector>
Вопрос - а никак не получается сделать RatingBar таким, чтобы он звездочки обрисовывал в зависимости от своего роста? Чтобы не пришлось делать отдельный  drawable  который по сути дублирует уже существующий, но делает его меньше?

Если что можешь мне написать, попробуем вместе разобраться, но я сам пока хз, с RatingBar-ом не работал

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/res/drawable/ratingbar_svg_small_selector.xml
> +</layer-list>
Здесь тоже вопрос касательно того, нужно ли делать отдельный drawable для звездочки поменьше, или можно как-то rating bar звезды в зависимости от высоты рисовать

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +            <com.google.android.material.card.MaterialCardView
Все что внутри materialcrdview и его самого ты можешь вынести в отдельный лейаут - это тебе в любом случае понадобиться для того чтобы потом делать следующую домашку по спискам.

А здесь можешь просто пока include сделать

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +            android:layout_marginStart="16dp"
здесь можешь добавить гайдлайны и убрать marginStart , точно так же как и marginTop

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +            tools:ignore="MissingConstraints" />
Этот игнор тоже можешь убрать - он тут бесполезен + сам warning который "MissingConstraints" - полезный и лучше его видеть , чем игнорировать

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +            app:layout_constraintGuide_begin="205dp"
вместо этой строчки лучше использовать 
app:layout_constraintGuide_percent="0.5"

Потому что ширина экранов может быть разная и центр не всегда будет там где 205dp

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +            app:layout_constraintTop_toBottomOf="@+id/fragment_movie_list_tv_movies_list">
В вот этот констрейнт уже можешь endToStartOf="guideline" сделать, тогда он у тебя и отцентруется правильно и Марины можно будет правильно поставить и паддинги и вообще все что нужно и будет место правильное занимать, а не как сейчас на скрине ниже

<img width="311" alt="image" src="https://user-images.githubusercontent.com/23121846/100812099-40d8ac80-344d-11eb-9503-b7e22ffaccfe.png">

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +                android:layout_marginEnd="6dp"
после того как вынесешь расставь паддинги и Маргины правильно - то есть условно у тебя не должен знать этот лейаут о том что ему именно нужно marginEnd=6, потому что он формально будет и в правой нижней позиции и в остальных

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +                    android:layout_width="match_parent"
когда вынесешь, можешь попробовать избавиться от лишних вложенностей и все в одном Constraint-лейауте сделать.  (но если что можешь и так оставить, тоже норм, не критично)

Я сам так редко делаю, но сейчас смотрю домашки -и  действительно красиво получается (если сам лейаут не пипец какой сложный и огромный )

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +                            app:layout_constraintTop_toTopOf="parent" />
Если сейчас попробовать сломать эту вьюху (хоть это и нереальный кейс) то вот что получается
<img width="124" alt="image" src="https://user-images.githubusercontent.com/23121846/100812604-75009d00-344e-11eb-8eb5-25eae13ffa33.png">

Здесь можно сделать wrap-content ширину и 0 dp высоту, добавить параметр 
который отвечает за aspectRatio: app:layout_constraintDimensionRatio="1:1"
В итоге у тебя получится что эта вьюха всегда будет квадратной даже на разных строках:
![Uploading image.png…]()

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +                            android:layout_marginTop="214dp"
Как по мне лучше убрать такой большой marginTop и оставить mrginBottom

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +                            app:layout_constraintTop_toTopOf="parent"
здесь ты можешь добавить констрейнты к вьюги на которой 13+, чтобы у тебя сердечко центровалось по этой вьюхе вертикально. Сейчас оно вообще не центруется

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +                            app:layout_constraintTop_toBottomOf="@+id/fragment_movie_list_tv_movie_genres" />
здесь (или на звездочках) нужно добавить констрейнт чтобы они по вертикали центровалиесь друг относительно друга, а то сейчас не так:

<img width="461" alt="image" src="https://user-images.githubusercontent.com/23121846/100812941-41724280-344f-11eb-9db8-b162deb0601d.png">

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +                        android:layout_marginStart="8dp"
<img width="360" alt="image" src="https://user-images.githubusercontent.com/23121846/100812977-5949c680-344f-11eb-8ba7-0c7057bb610f.png">
К маргин start можешь добавить marginEnd чтобы они были симметричны, а не как на скрине сейчас

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +                        android:layout_width="match_parent"
0dp должно быть и констрейнты расставлены

2020-12-02 00:38 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +                        android:layout_marginStart="8dp"
для маргин старта должен быть симметричный marginEnd

2020-12-06 09:43 UTC, AGENTxXx commented on app/src/main/res/drawable/ic_aim.xml
> +        <item android:offset="0" android:color="#FF3466"/>
Тут пробовал ссылаться, не видит этот цвет. Возможно из-за того, что внутри вставки aapt:attr уже находимся и это другая область видимости

2020-12-06 09:48 UTC, AGENTxXx commented on app/src/main/res/values/strings.xml
> +    <string name="movie_list_movies_list">Movies list</string>
Но тут ведь тогда несоответствие имен будет, что плохо. Значит имена у всех этих строк придется как-то изменять...

2020-12-06 10:14 UTC, AGENTxXx commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +                listener?.doBack()
А в чем разница между requireActivity().onBackPressed() и activity?.onBackPressed()?

2020-12-06 10:49 UTC, AGENTxXx commented on app/src/main/res/layout/fragment_movies_list.xml
> +                            app:layout_constraintTop_toBottomOf="@+id/fragment_movie_list_tv_movie_genres" />
Я пробовал так делать, но тогда выглядит как-то криво и приходится использовать app:layout_constraintVertical_bias="0.6", а это я думаю как-то не правильно. Так же можешь сам увидеть, что почему-то в блоке текста внутренний отступ сверху кажется больше, чем снизу, хотя padding отсутствует везде. Я пока добавил app:layout_constraintVertical_bias="0.6", но думаю это не правильно

2020-12-06 10:52 UTC, AGENTxXx commented on app/src/main/res/layout/fragment_movies_list.xml
> +                        android:layout_width="match_parent"
У меня этот блок в linerLayout, так что не могу 0dp ставить. в liner засунул, так как более удобная структура получается, как по мне.

2020-12-06 11:20 UTC, AGENTxXx commented on app/src/main/res/drawable/ic_liked.xml
> +      android:fillColor="@color/red_radical"
Пока так оставлю. Как функционал на лайк накидывать буду, переделаю. Чтобы если вдруг какие косяки появятся, было удобнее править.

2020-12-06 11:25 UTC, AGENTxXx commented on app/src/main/res/drawable/ic_star_off_small.xml
> +</vector>
Я тогда искал инфу про это (ну и сейчас тоже поискал). Вроде как и в самой андроид платформе такая же логика (https://stackoverflow.com/questions/12382632/how-to-set-the-custom-size-of-the-stars-in-ratingbar), у них разные стили под разные размеры. Возможно как-то в описании к селектору ratingbar_svg_small_selector.xml можно указать параметрами размер и использовать один файл со звездой, но пока тоже не нашел. Если прописывать, например android:height="10dp", то появляется notice "Override resource in drawable-v23. Я думаю, что это не хороший знак.

2020-12-06 16:06 UTC, Vladuken commented on app/src/main/res/drawable/ic_aim.xml
> +        <item android:offset="0" android:color="#FF3466"/>
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/23121846/101285381-e8f7c800-37f5-11eb-810c-301463f455ae.png">
Я сейчас глянул - можно так сделать, там этот градиент на самом деле не особо понятно зачем и можно убрать

2020-12-06 16:08 UTC, Vladuken commented on app/src/main/res/drawable/ic_star_off_small.xml
> +</vector>
Понял

2020-12-06 16:23 UTC, Vladuken commented on app/src/main/res/values/strings.xml
> +    <string name="movie_list_movies_list">Movies list</string>
Нейминг - это вещь, необходимая для удобства программиста, чтобы потом удобно было и понятно искать и использовать их.

А тут такая ситуация, что :
1. Этот текст отвечает за одну и ту же вещь на обоих экранах, и если он изменится , то нужно будет менять текст в двух строках.
2. Второй пункт более важный - формально в будущем эти строки будут динамичные и для каждого фильма свои, поэтому их вообще не будет в strings.xml.
Поэтому сейчас можно вот эти динамичные данные - использовать для них одну и ту же стрингу. Все равно потом выпилится (потому что сейчас хардкодим)

2020-12-06 16:26 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +                listener?.doBack()
Если кратко - то у нас фрагмент может быть в состоянии, когда он еще не прикреплен к Activity. 
И поэтому у фрагмента есть просто геттер, который nullable

А еще есть метод requireActivity() - он non-nullable. Но его можно вызывать только когда фрагмент приаттачен. Если память не изменяет, то requireActivity() можно без проблем вызывать в onViewCreated() и далее

2020-12-06 16:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +                listener?.doBack()
https://stackoverflow.com/questions/60402490/difference-between-getcontext-and-requirecontext-when-using-fragments

Нашел на стеке ответ, он про context, но аналогично про activity.

2020-12-06 17:11 UTC, Vladuken requested changes

2020-12-06 17:11 UTC, Vladuken commented on app/build.gradle
> +    //implementation 'androidx.legacy:legacy-support-v4:1.0.0'
такие комментарии можно удалять, потому что они не будут возвращаться потом, они просто выпиливаются

2020-12-06 17:11 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +import android.content.Context
После изменений прожимай в файле CTRL + SHIFT + L  - чтобы оптимизировать импорты (автоматически убрать ненужные) и отформатировать код

2020-12-06 17:11 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +                requireActivity().onBackPressed()
я обычно в onCreateView() использую requireActivity(), так что удали вторую строку (плюс больший косяк в том что ты две строки тут оставил, и условно, они могут обе и отработать)

2020-12-06 17:11 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/MainActivity.kt
> +    //private lateinit var fragmentMoviesList:FragmentMoviesList
все эти комментарии тоже можно удалить

2020-12-06 17:11 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +            app:layout_constraintGuide_begin="56dp" />
Заметил еще что ты можешь кнопочку Movies которая вверху экрана привязать к этому гайдлайну (но привязать его сверху)
Чтобы не было как сейчас:
<img width="232" alt="image" src="https://user-images.githubusercontent.com/23121846/101286598-67576880-37fc-11eb-8238-fe47577fb200.png">

Еще можно сделать так:
Ты в textView можешь добавить startDrawableCompat + iconPadding, чтобы это все было одной вьюшкой, а не двумя, как у тебя сейчас:
<img width="232" alt="image" src="https://user-images.githubusercontent.com/23121846/101286619-89e98180-37fc-11eb-9034-a3865c9643d0.png">

2020-12-06 17:11 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +                app:layout_constraintBottom_toBottomOf="parent"
Вот этот инклюд у тебя сейчас лежит внутри constraintlayout внутри еще одного constraintlayout.
Ты можешь эту вложенность убрать, оставив внешний констрейт лейаут только.

Только тебе нужно item_movie переделать чтобы оно было гибкое, а не с захардкоженными размерами.(сделать это нужно потому что телефоны разные и даже ширина у них разная а мы хотим чтобы они всегда отображались адекватно, в следующей домашке это заметнее будет, когда будет RecyclerView.)

Вот пример того что будет если например экран у нас будет узкий или какой-то еще не такой

2020-12-06 17:11 UTC, Vladuken commented on app/src/main/res/layout/item_movie.xml
> +
Хоть линеар лейатом и удобно пользоваться, можешь попробовать немного по другому сделать иерархию вьюшек, и вместо того чтобы запихивать в LinearLayout КонстрейнтЛейаут и пару текст вьюшек, ты можешь в констрейнт впихнуть линеар лейаут с этими текст вьюшками. Сильно это ничего не изменит, но как мне кажется, чище будет сам файл лейаута.

2020-12-06 17:11 UTC, Vladuken commented on app/src/main/res/layout/item_movie.xml
> +        android:layout_height="296dp"
Попробуй здесь переделать так, чтобы это было match_parent

2020-12-06 17:11 UTC, Vladuken commented on app/src/main/res/layout/item_movie.xml
> +                    android:layout_height="248dp"
c картинкой тоже попробуй сделать 0dp/0dp + centerCrop - чтобы на разных экранах оно адаптивно отображалось

2020-12-06 17:11 UTC, Vladuken commented on app/src/main/res/layout/item_movie.xml
> +                    app:layout_constraintEnd_toEndOf="parent"
end_to_end не туда поставлен:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/23121846/101287009-d635c100-37fe-11eb-9d10-7dd953229891.png">

2020-12-06 17:11 UTC, Vladuken commented on app/src/main/res/layout/item_movie.xml
> +                    app:layout_constraintVertical_bias="0.6" />
Я бы тут поигрался с gravity - но если не получится, то либо так оставь, либо забей вообще и удали этот layout_constraintVertical_bias

2020-12-06 17:11 UTC, Vladuken commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
вот это можно удалить

2020-12-06 18:36 UTC, AGENTxXx commented on app/src/main/res/layout/item_movie.xml
> +                    app:layout_constraintVertical_bias="0.6" />
Я лучше оставлю первый вариант, где был отступ сверху 2dp, т.к. там нормально по центру получается. Гравити ни как не помогло. Косяк скорее всего из-за того, что верхняя часть звезды выходит за границу самого ratingBar,

2020-12-16 22:28 UTC, Vladuken requested changes
Прокомментил

2020-12-16 22:28 UTC, Vladuken commented on app/build.gradle
> +    implementation 'com.github.bumptech.glide:glide:4.4.0'
можно обновить зависимость, вроде есть новая версия глайда

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/ActorListAdapter.kt
> +    }
это неиспользуемый код - лучше его удалять (ну или использовать там где он нужен)

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/ActorListAdapter.kt
> +    fun onBlind(actor:Actor) {
название метода должно быть onBind

А вообще лучше bind - потому что приставка on....... обычно для коллбеков - типо onItemClicked.
А bind - означает что этот метод биндит данные (а не уведомляет что билдинг произошел)

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/ActorListAdapter.kt
> +        img.setImageResource(imgPreview)
Кстати, интересное решение для того чтобы доставать ресурс из сохраненных, но потом это нужно будет удалить, когда будет подзагрузка с Нетворка

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/ActorListAdapter.kt
> +    get() = this.itemView.context
А вот это как мне кажется лучше удалить - оно наоборот только путает.
Контекста ведь у ViewHolder-a нет, а он у ItemView

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +    private lateinit var movie:Movie
Лучше Movie не хранить  полем класса, а можно просто достать из аргументов в onViewCreated

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +    private lateinit var rv: RecyclerView
точно так же думаю что и ссылку на recyclerView можно не хранить полем, потому что он используется только в одном методе жизненного цикла и не нужен в других

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +        var stars: RatingBar = view.findViewById(R.id.activity_movie_details_rb_rating)
здесь можно придерживаться одного форматирования - потому что в одних случаях ты указываешь тип явно 
val genres: TextView

а в других внутри findViewById

 val rating = view.findViewById<TextView>

Просто приятнее будет если не мешать а сделать все одинаково

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +            movie.reviewCount.toString()
Смотри, у тебя сейчас строка такая:
 <string name="movie_reviews_count">%1$s reviews</string>

но если ее сделать 
 <string name="movie_reviews_count">%1$d reviews</string>
То ты сможешь в getString() прикидывать  movie.reviewCount без .toString()

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +        )
вижу подобный код уже второй раз

думаю что было бы неплохо вынести это в отдельный метод типо getMovieImageId 

Потому что так уберем дублирование и еще потом нам придется это удалять, и удалять будет проще

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +        rv.adapter = adapter
вот тут по сути можно и проинициализировать val с RecyclerView, а не держать ее полем класса

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +        adapter.notifyDataSetChanged()
из интересного кстати, notifyDataSetChanged можно спрятать внутри bindActors

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +            movie = it.getParcelable("movie")!!
Во первых , Movie лучше не хранить полем класса, если он нигде кроме места получения больше не используется
Во вторых у тебя строка "movie" 2 раза используется - намного красивее было бы вынести ее в приватную константу и ссылаться на нее 
Ну и в третьих - оператор !! в Котлин был именно двумя восклицательными знаками указан, чтобы явно привлечь внимание разработчика и показать что "ТЫ ТУТ МОЖЕШЬ ВСЕ ПРИЛОЖЕНИЕ УРОНИТЬ!!!!!", поэтому они выбрали 2 восклицательных знака. И поэтому !! лучше использовать по минимуму и только в тех местах где ты прям явно контролируешь, что если все таки вызовется !!, то это значит что приложение стоит уронить, потому что дальше оно уже не отработает.

Чуть ниже я покажу красивое решение как это можно обойти

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +            }
собственно касательно красивого решения - 
<img width="560" alt="image" src="https://user-images.githubusercontent.com/23121846/102410256-5a5b2600-4001-11eb-8c6b-22cdbd3870b6.png">

Скажу честно - можно делать как тебе удобнее, я для себя придумал такую штуку:

Мы наш парселабл прячем в экстенш, в результате чего в newInstance мы явно сети
<img width="461" alt="image" src="https://user-images.githubusercontent.com/23121846/102410445-9ee6c180-4001-11eb-93b8-db73f18159c0.png">

а внутри фрагмента достаем ее так: 
<img width="173" alt="image" src="https://user-images.githubusercontent.com/23121846/102410506-b160fb00-4001-11eb-973c-675bab0c9ae8.png">


В результате чего мы вынесли логику по добавлению в бандл и считывание из бандла в другое место, а также если мы каким то образом забыли в коде прокинуть в бандл наш Parcelable, то выкинется ошибка , типо "вы забыли добавить бандл, добавьте его"

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesList.kt
> +    private var listener: CardFragmentClickListener? = null
предлагаю просто прикидывать в конструктор MovieListAdapter лямбду с типом (Movie)-> Unit
Тогда можно будет убрать кучу лишнего кода, а результат такой же будет

Вот в конструктор лямбду прокидываем:
`class MovieListAdapter(private val onMovieClicked: (Movie) -> Unit) `
В результате у тебя будет вот так вот
```
private var adapter = MovieListAdapter {
        listener?.cardClick(it)
    }
```

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesList.kt
> +    private lateinit var rv: RecyclerView
точно также rv я бы здесь убрал из полей класса

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesList.kt
> +        }
вот это для красоты я бы просто вынес в отдельный приватный метод setupGridLayoutManager
(и сетапил бы его уже тут, а не в xml, чтобы держать количество ячеек для разных конфигураций  в одном месте (ну и убрал бы из xml))

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesList.kt
> +        adapter.notifyDataSetChanged()
то же самое, adapter.notifyDataSetChanged можно спрятать внутрь

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/MovieListAdapter.kt
> +class MovieListAdapter: RecyclerView.Adapter<MovieViewHolder>() {
1. Сюда в конструктор лямбду, как я выше уже описал

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/MovieListAdapter.kt
> +    private var movies:List<Movie> = listOf()
можно здесь вместо listOf() указать emptyList() - разницы нет , но мб читаться проще будет

Еще если захочешь, можешь попробовать private var movies в конструктор вынести, чтобы если пользовательь класса захочет при конструировании адаптера сразу данные прокинуть ,он мог это сделать используя конструктор

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/MovieListAdapter.kt
> +            (holder.itemView.context as FragmentMoviesList.CardFragmentClickListener).cardClick(movies[position])
вот так делать - очень плохо, потому что в таком случае наш класс адаптера напрямую знает о том, где он используется в текущий момент (то есть явно указано что он `as FragmentMoviesList.CardFragmentClickListener)`)

Более красивым и правильным решением будет как я уже выше описал, прокинуть лямбду в конструктор, и просто вызвать ее здесь передав в нее movies[position]

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/MovieListAdapter.kt
> +    }
тоже неиспользуемый код

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/MovieListAdapter.kt
> +    var like:ImageView = itemView.findViewById(R.id.fragment_movie_list_img_movie_like)
можешь чисто для себя сделать эти переменные private, чтобы только ViewHolder мог ими пользоваться
а метод bind уже публичным

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/MovieListAdapter.kt
> +    fun onBlind(movie:Movie) {
Лучше название bind() вместо onBlind()

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/MovieListAdapter.kt
> +        img.setImageResource(imgPreview)
в 3й раз вижу такой код , можно экстеншн использовать, который к этому моменту уже должен быть где-то

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/MovieListAdapter.kt
> +    get() = this.itemView.context
я бы это тоже удалил

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/data/Actor.kt
> +    val name: String? = null
Actor-а можно сделать с полями которые будут не nullable

<img width="219" alt="image" src="https://user-images.githubusercontent.com/23121846/102412372-6eeced80-4004-11eb-9c6b-d83ce95bba6a.png">

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/data/Movie.kt
> +    val detailLink:String? = null,
здесь точно так же - все эти поля можно сделать не nullable

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/data/Movie.kt
> +    val detailLink:String? = null,
Ну и не обязательно им давать дефолтные значения

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/data/Movie.kt
> +    val rating:String? = null,
рейтинг можно Int сделать ,потому что это просто цифра на которой указан возраст (хотя если какие то другие рейтинги будут, то можно в будущем будет поменять на string, или на enum даже, в зависимости от того какие там рейтинги)

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +            app:layout_constraintStart_toStartOf="parent" />
почти все гайдлайны можешь поудалять, потому что они уже и не нужны особо, так как мы теперь используем RecyclerView

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +            android:drawableStart="@drawable/ic_aim"
drawableStartCompat

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +            android:layout_height="match_parent"
0dp и правильно расставленные констрейнты

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +            android:foregroundGravity="center_horizontal"
форграунд Гравити кажется тут ничего не делает

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +            app:layoutManager="androidx.recyclerview.widget.GridLayoutManager"
я бы это из кода сетил, потому что ты обрабатываешь еще Landscape там из кода, и держал бы обе цифры там уже

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/res/layout/view_holder_actor.xml
> +    android:layout_marginStart="8dp">
можешь почитать про ItemDecorator-ы в RecyclerView и про то как сделать SpaceItemDecorator, чтобы не пришлось расставлять маргины , либо как более быстрое решение , можешь оставить как есть (но тогда у тебя в конце не будет этого маргиналии, потому что marginstart)

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/res/values/strings.xml
>      <string name="movie_details_actor1">Robert Downey Jr.</string>
Кстати, забыл сказать - такие строки которые остались только для отображения в LayoutEditor ты можешь использовать внутри через tools:text, а не через android:text.

потому что если ты через андроид, то оно установится в твоем приложении, и иногда если сеттинг текста из кода будет слишком медленный, на долю секунды будет виден старый текст, а это уже небольшой баг

2020-12-16 22:28 UTC, Vladuken commented on app/src/main/res/values/strings.xml
> +    <string name="movie_list_movie_length">%1$s min</string>
здесб ты можешь вместо %1$s использовать %1$d, что позволит подставлять цифры. 

Можешь поискать еще как можно форматировать , там достаточно много всего есть

2020-12-18 15:35 UTC, AGENTxXx commented on app/src/main/res/values/strings.xml
> +    <string name="movie_list_movie_length">%1$s min</string>
Да, чет не подумал об этом. Поменял на d

2020-12-18 15:36 UTC, AGENTxXx commented on app/src/main/res/values/strings.xml
>      <string name="movie_details_actor1">Robert Downey Jr.</string>
Да, хорошее замечание.

2020-12-18 15:54 UTC, AGENTxXx commented on app/src/main/res/layout/view_holder_actor.xml
> +    android:layout_marginStart="8dp">
Решил оставить так как есть, но на гите нашел и сохранил себе в gist. Но по моему мнению это не очень удобное решение и редко кто-то будет в таком проекте это использовать (хотя, могу ошибаться). А чтобы в конце был margin 8dp, то я бы просто добавил отступ у rv и все. Тогда была би иллюзия того, что всё ок.

2020-12-18 15:56 UTC, AGENTxXx commented on app/src/main/res/layout/fragment_movies_list.xml
> +            app:layoutManager="androidx.recyclerview.widget.GridLayoutManager"
Могу ошибаться, но так сделал, т.к. если в код бы убрал, то превью бы не заработало, а так можно в превью сразу же смотреть, как это выглядит.

2020-12-18 15:57 UTC, AGENTxXx commented on app/src/main/res/layout/fragment_movies_list.xml
> +            android:foregroundGravity="center_horizontal"
Ну да, разницы нет, если убрать.

2020-12-18 15:59 UTC, AGENTxXx commented on app/src/main/java/com/smog/courseproject/ActorListAdapter.kt
> +    get() = this.itemView.context
Это не моя идея, это идея из воркшоп. Сам-то такое не практиковал, но все таки, мне показалось, удобно, т.к. пишешь контекст, а он работает хД

2020-12-18 16:07 UTC, AGENTxXx commented on app/src/main/java/com/smog/courseproject/ActorListAdapter.kt
> +    fun onBlind(actor:Actor) {
Да, опечатка моя, но в воркшопе почему-то onBind... Тогда опять не понятно, как эе правильно...

2020-12-18 16:12 UTC, AGENTxXx commented on app/build.gradle
> +    implementation 'com.github.bumptech.glide:glide:4.4.0'
Лучше, как использовать буду, тогда уже и обновлю. Вдруг какой гемор выскочит с этим обновлением)

2020-12-18 16:18 UTC, AGENTxXx commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +        var stars: RatingBar = view.findViewById(R.id.activity_movie_details_rb_rating)
Да, хорошее замечание!

2020-12-18 16:29 UTC, AGENTxXx commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +        adapter.notifyDataSetChanged()
Да, но я тут так же по примеру воркшопа делал

2020-12-18 16:53 UTC, AGENTxXx commented on app/src/main/java/com/smog/courseproject/MovieListAdapter.kt
> +    private var movies:List<Movie> = listOf()
Да, хорошая идея. По поводу emptyList() решил оставить пред. значение, т.к. не сказал бы, что читается проще.

2020-12-18 17:19 UTC, AGENTxXx commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +            }
Это решение меня так и не избавило от !!, а вроде как это и была цель.

2020-12-18 18:37 UTC, AGENTxXx commented on app/src/main/java/com/smog/courseproject/FragmentMoviesList.kt
> +        }
Решил как есть ставить, т.к. я не совсем понимаю, если убрать из xml, то превью все упадет ведь, а если и там и там оставить, значит могут быть разногласия и еще и лишняя строка добавляется.

2020-12-19 03:43 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesList.kt
> +        }
Чтобы из превью не пропало - можешь поставить tools:layoutManager вместо android:layoutManager

  ```
<androidx.recyclerview.widget.RecyclerView
            android:id="@+id/fragment_movies_list_rv"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginTop="30dp"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/fragment_movie_list_tv_movies_list"
            tools:layoutManager="androidx.recyclerview.widget.GridLayoutManager"
            tools:listitem="@layout/view_holder_movie"
            tools:spanCount="2" />

```
В итоге у тебя превью будет таким каким ты его хочешь видеть в Layout editor-е, а из кода настроишь то каким он уже будет в самом приложении

2020-12-19 03:47 UTC, Vladuken commented on app/build.gradle
> +    implementation 'com.github.bumptech.glide:glide:4.4.0'
ок, но в будущем старайся добавлять сразу новые версии

2020-12-19 03:48 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/ActorListAdapter.kt
> +    fun onBlind(actor:Actor) {
Ну ладно, это уже вопросы нейминга)
Я обычно просто bind() как действие использую, и мне кажется что лучше его, но тут и то и то ок

2020-12-19 03:51 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/ActorListAdapter.kt
> +    get() = this.itemView.context
Я вижу тут тогда два варианта:

Либо этот экстеншн вынести в какое-то общее место (хоть мне это не сильно нравится), чтобы не пилить два одинаковых экстеншона в разных местах

Либо все таки взять itemView.context (мне этот вариант больше нравится в долгосрочной перспективе, чем такой экстенш)

Тут уже реши сам как тебе удобнее будет работать, и сделай так. Ну да, на крайняк можно оставить этот экстеншн в каждом классе вьюхолдеров которые будешь делать, но тогда у тебя в каждом классе будет 2 доп.строчки

2020-12-19 03:54 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +            app:layoutManager="androidx.recyclerview.widget.GridLayoutManager"
я там чуть выше уже кидал, но продублирую как можно сделать и сюда
вынести в Тулы
```
<androidx.recyclerview.widget.RecyclerView
          android:id="@+id/fragment_movies_list_rv"
          android:layout_width="match_parent"
          android:layout_height="match_parent"
          android:layout_marginTop="30dp"
          app:layout_constraintBottom_toBottomOf="parent"
          app:layout_constraintEnd_toEndOf="parent"
          app:layout_constraintStart_toStartOf="parent"
          app:layout_constraintTop_toBottomOf="@+id/fragment_movie_list_tv_movies_list"
          tools:layoutManager="androidx.recyclerview.widget.GridLayoutManager"
          tools:listitem="@layout/view_holder_movie"
          tools:spanCount="2" />
```

2020-12-19 03:58 UTC, Vladuken commented on app/src/main/res/layout/view_holder_actor.xml
> +    android:layout_marginStart="8dp">
Хорошо, можешь и так оставить 
Но касательно не очень удобного решения - могу немного оспорить. 
Ну, то есть то что декораторы кастомные достаточно трудно пилить - это да
Но они как мне кажется, все-таки много где используются, потому что они правильно отработают как на первых элементах списка, так и на последних. А паддинг/маргин у элемента списка только на первом элементе отработает. Тут опять же надо смотреть насколько важно чтобы прям идеально отображалось. Так что да, условно можешь забить, но и декораторы не просто так ввели отдельной сущностью)

2020-12-19 03:59 UTC, Vladuken commented on app/src/main/res/layout/view_holder_actor.xml
> +    android:layout_marginStart="8dp">
А вот касательно отступа у самого rv- тут как повезет)

2020-12-19 04:00 UTC, Vladuken commented on app/src/main/res/layout/view_holder_actor.xml
> +    android:layout_marginStart="8dp">
А вот касательно отступа у самого rv- тут как повезет)

2020-12-19 04:05 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +            }
Прошу прощения - мой косяк, я немного подредачил для скрина не посмотрев на результаты.
Но собственно что я имел в виду:

```
var Bundle?.movie :Movie
    set(value) {
        this?.putParcelable("movie",value)
    }
    get() {
        return  this?.getParcelable("movie")
            ?: throw IllegalArgumentException("Provide movie")
    }
```

Экстеншн не на типе Bundle, а на типе Bundle? 

Тогда то что я имел в виду будет работать красиво - и кидать нам ошибку только если мы как программисты забудем запровайдить аргументы в фрагмент

Попробуй так сделать - и тогда можно будет использовать 
`arguments.movie` без проблем

2020-12-19 04:12 UTC, Vladuken requested changes

2020-12-19 04:12 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/FragmentMoviesDetails.kt
> +            ?: throw IllegalArgumentException("Provide movie")
вот это вынеси в companion object , пусть там лежит этот код

2020-12-19 04:12 UTC, Vladuken commented on app/src/main/java/com/smog/courseproject/Utils.kt
> +object Utils {
кстати, ты можешь не делать Object, а просто сделать topLevel функцию - чисто внутри файла 

просто объект тут особо и не нужен, как мне кажется 

типо в джазе нужен для статических методов класс, а в Котлин можно в файле сколько угодно методов просто описать

2020-12-20 10:00 UTC, AGENTxXx commented on app/src/main/java/com/smog/courseproject/FragmentMoviesList.kt
> +        }
Да, это я понимаю, но это лишняя строка и, если идти от того, что "Лучше добавить в код, чем в xml", но тогда и binding это плохая технология, т.к. получается обработка отправляется в xml часть и так же теряется разделение и наглядность. Но многие считают, что это отличная технология.

2020-12-20 10:05 UTC, AGENTxXx commented on app/src/main/java/com/smog/courseproject/Utils.kt
> +object Utils {
Да, я знаю это, но не лучше ли создать Util область, по которой будет ясно, что эта функция из вспомогательного класса?

2020-12-20 10:12 UTC, AGENTxXx commented on app/src/main/java/com/smog/courseproject/ActorListAdapter.kt
> +    get() = this.itemView.context
Пока оставлю все таки как есть, нужно нормально пообщаться по этому вопросу, чтобы я непосредственно сам догнал, что то, что ты говоришь, гораздо лучше, чем это решение. Это относительно простой класс, но он может быть гораздо сложнее, и постоянно писать itemView.context это дополнительное время.

2020-12-20 10:25 UTC, AGENTxXx commented on app/src/main/res/layout/fragment_movies_list.xml
> +            app:layout_constraintStart_toStartOf="parent" />
Я 1 гайдлайн удалил, но другие 2 нельзя удалить, т.к. по ним есть привязка. Я не совсем понял, если честно. Ты мне сам сказал, что лучше их поставить, т.к. Movies List можно будет быстро подвинуть, если что изменится, хотя в начале он у меня был на margin. В общем, мне показалось, что есть тут в чем то смысл, поэтому я и перешел в гайдлайны.

2020-12-21 21:13 UTC, merged